name: E2E Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        shell: bash
        run: |
          docker buildx bake -f compose.yaml --set="*.cache-to=type=gha,mode=max" --set="*.cache-from=type=gha" --load

      - name: Setup web server
        shell: bash
        run: |
          docker compose up --exit-code-from playwright --abort-on-container-exit --remove-orphans
          docker compose logs -f
          docker compose down
        env:
          HEADLESS: false
          CI: true
          SLOW: true
          CHROME_STORE: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            packages/e2e/playwright-report*

      - name: Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Tests
          working-directory: packages/e2e
          path: ./playwright-report/junit.xml
          # Waiting for https://github.com/dorny/test-reporter/issues/506
          reporter: java-junit
          only-summary: false
          max-annotations: 10
          fail-on-error: true
